language: python
python:
  - "3.6.5"
  
install:
  - pip install healpy matplotlib
  - python setup.py sdist
  - python setup.py install
  - cd /home/travis/build/fincardona/ScanningTools.py/ScanningTools
  - travis_wait 200 mvn -e -X install
  
# command to run tests
script:
  - pytest
  
