language: python
python:
  - "3.6.5"
  
install:
  - pip install healpy matplotlib
  - python setup.py sdist
  - python setup.py install
  - travis_wait mvn install
  #- travis_wait 200 mvn install
  
# command to run tests
script:
  - pytest
  
